version: "3.8"
services:

    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        working_dir: /var/www/
        volumes:
            - ./:/var/www/
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/logs/:/var/log/nginx/
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
